#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page
#+ The redirection must be 301 Moved Permenently

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
newredirect="\\\trewrite ^/redirect_me https://www.google.com/ permanent;"
sudo sed -i "26i $newredirect" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
