#!/usr/bin/env bash
# Dispalys "To infinty and beyond" indfinitely with a sleep 2 inbetween each iteration and "I am invincible!!!" when recieving a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
