#!/usr/bin/env bash
# This script prints "Best School" 10 times but "Hi" for the 9th

i=1
while [ $i -lt 10 ]
      do
      echo "Best School"
      if [ $i -eq 8 ]
      then
	  echo "Hi"
      fi
      (( i+=1 ))
done
