#!/usr/bin/env bash
# Displays "bad luck" for the 4th iteration
# Displays "good luck" for the 8th iteration
# Displays "Best school" for the other iterations

counter=1
while [ "$counter" -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( counter+=1 ))
done
