#!/usr/bin/env bash
# A bash script that creates a RSA key pair with:
#   Name of the created private key must be school
#   Number of bits in the created key to be created 4096
#   The created key must be protected by the passphrase betty

ssh-keygen -f school -b 4096 -N betty
